const categories = [
  { id: "cpu", label: "CPU" },
  { id: "gpu", label: "显卡" },
  { id: "motherboard", label: "主板" },
  { id: "memory", label: "内存" },
  { id: "storage", label: "固态" },
  { id: "psu", label: "电源" },
  { id: "case", label: "机箱" },
  { id: "cooler", label: "散热" },
];

const rawParts = [
  {
    id: "cpu-7800x3d",
    category: "cpu",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    basePrice: 2399,
    socket: "AM5",
    memory: "DDR5",
    wattage: 120,
    score: 96,
    tags: ["游戏神U", "AM5", "8核16线程"],
  },
  {
    id: "cpu-9700x",
    category: "cpu",
    name: "AMD Ryzen 7 9700X",
    brand: "AMD",
    basePrice: 2199,
    socket: "AM5",
    memory: "DDR5",
    wattage: 88,
    score: 91,
    tags: ["低功耗", "AM5", "Zen 5"],
  },
  {
    id: "cpu-14700kf",
    category: "cpu",
    name: "Intel Core i7-14700KF",
    brand: "Intel",
    basePrice: 2449,
    socket: "LGA1700",
    memory: "DDR5",
    wattage: 190,
    score: 92,
    tags: ["生产力", "LGA1700", "20核"],
  },
  {
    id: "cpu-14600kf",
    category: "cpu",
    name: "Intel Core i5-14600KF",
    brand: "Intel",
    basePrice: 1599,
    socket: "LGA1700",
    memory: "DDR5",
    wattage: 155,
    score: 86,
    tags: ["高性价比", "LGA1700", "14核"],
  },
  {
    id: "gpu-4070s",
    category: "gpu",
    name: "NVIDIA GeForce RTX 4070 SUPER 12G",
    brand: "NVIDIA",
    basePrice: 4899,
    wattage: 220,
    length: 300,
    score: 93,
    tags: ["2K高刷", "DLSS", "12GB"],
  },
  {
    id: "gpu-4070ti-s",
    category: "gpu",
    name: "NVIDIA GeForce RTX 4070 Ti SUPER 16G",
    brand: "NVIDIA",
    basePrice: 6399,
    wattage: 285,
    length: 336,
    score: 98,
    tags: ["4K入门", "16GB", "创作"],
  },
  {
    id: "gpu-7900gre",
    category: "gpu",
    name: "AMD Radeon RX 7900 GRE 16G",
    brand: "AMD",
    basePrice: 4199,
    wattage: 260,
    length: 320,
    score: 91,
    tags: ["大显存", "2K高刷", "16GB"],
  },
  {
    id: "gpu-4060ti",
    category: "gpu",
    name: "NVIDIA GeForce RTX 4060 Ti 8G",
    brand: "NVIDIA",
    basePrice: 2799,
    wattage: 165,
    length: 245,
    score: 78,
    tags: ["1080P", "低功耗", "8GB"],
  },
  {
    id: "mb-b650m",
    category: "motherboard",
    name: "B650M WiFi 重炮手",
    brand: "ASUS",
    basePrice: 1199,
    socket: "AM5",
    memory: "DDR5",
    wattage: 35,
    score: 88,
    tags: ["AM5", "DDR5", "WiFi"],
  },
  {
    id: "mb-x870",
    category: "motherboard",
    name: "X870 AORUS ELITE WiFi7",
    brand: "GIGABYTE",
    basePrice: 2299,
    socket: "AM5",
    memory: "DDR5",
    wattage: 45,
    score: 94,
    tags: ["AM5", "PCIe 5.0", "WiFi7"],
  },
  {
    id: "mb-b760m",
    category: "motherboard",
    name: "B760M 迫击炮 WiFi II",
    brand: "MSI",
    basePrice: 1299,
    socket: "LGA1700",
    memory: "DDR5",
    wattage: 38,
    score: 89,
    tags: ["LGA1700", "DDR5", "WiFi"],
  },
  {
    id: "mb-z790",
    category: "motherboard",
    name: "Z790 AERO G",
    brand: "GIGABYTE",
    basePrice: 2399,
    socket: "LGA1700",
    memory: "DDR5",
    wattage: 50,
    score: 94,
    tags: ["LGA1700", "DDR5", "扩展强"],
  },
  {
    id: "ram-32-6000",
    category: "memory",
    name: "32GB DDR5 6000 C30 套条",
    brand: "Kingston",
    basePrice: 799,
    memory: "DDR5",
    wattage: 12,
    score: 91,
    tags: ["32GB", "6000MHz", "低时序"],
  },
  {
    id: "ram-32-6400",
    category: "memory",
    name: "32GB DDR5 6400 RGB 套条",
    brand: "G.Skill",
    basePrice: 899,
    memory: "DDR5",
    wattage: 14,
    score: 92,
    tags: ["32GB", "6400MHz", "RGB"],
  },
  {
    id: "ram-64-6000",
    category: "memory",
    name: "64GB DDR5 6000 创作套条",
    brand: "Corsair",
    basePrice: 1499,
    memory: "DDR5",
    wattage: 18,
    score: 95,
    tags: ["64GB", "创作", "DDR5"],
  },
  {
    id: "ssd-1t",
    category: "storage",
    name: "1TB PCIe 4.0 NVMe SSD",
    brand: "WD",
    basePrice: 499,
    wattage: 7,
    score: 84,
    tags: ["1TB", "PCIe 4.0", "系统盘"],
  },
  {
    id: "ssd-2t",
    category: "storage",
    name: "2TB PCIe 4.0 NVMe SSD",
    brand: "Samsung",
    basePrice: 999,
    wattage: 8,
    score: 92,
    tags: ["2TB", "高性能", "缓存"],
  },
  {
    id: "ssd-4t",
    category: "storage",
    name: "4TB PCIe 4.0 NVMe SSD",
    brand: "Lexar",
    basePrice: 1699,
    wattage: 10,
    score: 93,
    tags: ["4TB", "素材库", "大容量"],
  },
  {
    id: "psu-650",
    category: "psu",
    name: "650W 金牌全模组 ATX 3.0",
    brand: "Seasonic",
    basePrice: 599,
    wattage: -650,
    capacity: 650,
    score: 86,
    tags: ["650W", "金牌", "ATX 3.0"],
  },
  {
    id: "psu-750",
    category: "psu",
    name: "750W 金牌全模组 ATX 3.1",
    brand: "SuperFlower",
    basePrice: 799,
    wattage: -750,
    capacity: 750,
    score: 91,
    tags: ["750W", "金牌", "静音"],
  },
  {
    id: "psu-850",
    category: "psu",
    name: "850W 白金全模组 ATX 3.1",
    brand: "Corsair",
    basePrice: 1099,
    wattage: -850,
    capacity: 850,
    score: 95,
    tags: ["850W", "白金", "高端"],
  },
  {
    id: "case-matx",
    category: "case",
    name: "紧凑 MATX 海景房机箱",
    brand: "Jonsbo",
    basePrice: 399,
    maxGpuLength: 330,
    wattage: 0,
    score: 82,
    tags: ["MATX", "330mm显卡", "玻璃侧透"],
  },
  {
    id: "case-airflow",
    category: "case",
    name: "高风道 ATX 中塔机箱",
    brand: "Fractal",
    basePrice: 699,
    maxGpuLength: 380,
    wattage: 0,
    score: 92,
    tags: ["ATX", "380mm显卡", "风道强"],
  },
  {
    id: "case-sff",
    category: "case",
    name: "ITX 铝合金小钢炮机箱",
    brand: "Lian Li",
    basePrice: 899,
    maxGpuLength: 322,
    wattage: 0,
    score: 88,
    tags: ["ITX", "322mm显卡", "小体积"],
  },
  {
    id: "cooler-pa120",
    category: "cooler",
    name: "双塔六热管风冷",
    brand: "Thermalright",
    basePrice: 199,
    cooling: 210,
    wattage: 4,
    score: 87,
    tags: ["风冷", "性价比", "双塔"],
  },
  {
    id: "cooler-240",
    category: "cooler",
    name: "240mm 一体式水冷",
    brand: "DeepCool",
    basePrice: 499,
    cooling: 250,
    wattage: 8,
    score: 90,
    tags: ["240水冷", "ARGB", "安静"],
  },
  {
    id: "cooler-360",
    category: "cooler",
    name: "360mm 高性能水冷",
    brand: "NZXT",
    basePrice: 899,
    cooling: 320,
    wattage: 12,
    score: 95,
    tags: ["360水冷", "高端", "屏显"],
  },
];

module.exports = { categories, rawParts };
